services:
  # 1. The PHP Engine (Running your Laravel code)
  app:
    build: .
    container_name: project1_php
    volumes:
      - .:/var/www/html
    environment:
      - TMPDIR=/var/www/html/storage/framework/cache
      - TEMP=/var/www/html/storage/framework/cache
    networks:
      - project-network

  # 2. The Web Server (Nginx) to make it accessible via your browser
  web:
    image: nginx:alpine
    container_name: project1_web
    ports:
      - "8085:80" # You will access this project at http://localhost:8001
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d # We'll create this config folder in the next step
    depends_on:
      - app
    networks:
      - project-network

networks:
  project-network:
    name: my-shared-network # Connects this project directly to your global database highway
    external: true